// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",
  options: {
    // Check for update on startup. Default: true
    checkForUpdate: false,
  },
  rewrite: [
    // Redirect all urls to use https
    {
      match: ({ url }) => url.protocol === "http",
      url: { protocol: "https" }
    },
    // Skip vk.com link tracking (vk.com/away.php)
    {
      match: /vk\.com\/away.php/,
      url: ({url}) => {
          const match = url.search.match(/to=(.+)/)
          return !match ? url : decodeURIComponent(decodeURIComponent(match[1]));
      }
    }
  ],
  handlers: [
    // Open scrumpoker on Google Chrome
    {
      match: /^https?:\/\/scrumpoker\-online\.org\/en\/room\/.*$/,
      browser: "Google Chrome"
    },
    // Open Zoom links in Zoom app
    {
      match: [
          "zoom.us/j/*",
          finicky.matchDomains(/.*\zoom.us\/j/),
          /zoom.us\/j\//,
      ],
      browser: "us.zoom.xos"
    },
    // Open Google Meet in Google Chrome if opened from Mattermost
    {
      match: ({opener, url}) =>
          opener.bundleId === "Mattermost.Desktop" && url.host.includes("meet.google.com"),
      browser: "Google Chrome"
    }
  ]
}
