[ -f $HOME/.dotfiles/zsh/zsh_config.zsh ] && source $HOME/.dotfiles/zsh/zsh_config.zsh
[ -f $HOME/.dotfiles/zsh/setopt.zsh ] && source $HOME/.dotfiles/zsh/setopt.zsh
[ -f $HOME/.dotfiles/zsh/exports.zsh ] && source $HOME/.dotfiles/zsh/exports.zsh
[ -f $HOME/.dotfiles/zsh/commands.zsh ] && source $HOME/.dotfiles/zsh/commands.zsh
[ -f $HOME/.dotfiles/zsh/aliases.zsh ] && source $HOME/.dotfiles/zsh/aliases.zsh
[ -f $HOME/.dotfiles/zsh/private_aliases.zsh ] && source $HOME/.dotfiles/zsh/private_aliases.zsh
[ -f $HOME/.dotfiles/zsh/asdf.zsh ] && source $HOME/.dotfiles/zsh/asdf.zsh
[ -f $HOME/.dotfiles/zsh/bindkeys.zsh ] && source $HOME/.dotfiles/zsh/bindkeys.zsh
[ -f $HOME/.dotfiles/zsh/history.zsh ] && source $HOME/.dotfiles/zsh/history.zsh
[ -f $HOME/.dotfiles/zsh/zcompdump.zsh ] && source $HOME/.dotfiles/zsh/zcompdump.zsh
