[tools]
node = "lts"
go = "latest"
python = "latest"
rust = "latest"
ruby = "latest"
usage = "latest"
uv = "latest"
bun = "latest"
chezmoi = "latest"
"github:Mayurifag/yawn" = "latest"
"github:Mayurifag/conditional-launcher" = "latest"
